#---------------------------------#
#       restore nuget packages    #
#---------------------------------#
before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

assembly_info:
  patch: false
 
build:
  parallel: true                     # enable MSBuild parallel builds
  project: ServiceBusExplorer.csproj # path to Visual Studio project

  # MSBuild verbosity level
  verbosity: normal                  # quiet|minimal|normal|detailed

#---------------------------------#
#      after build - create zip   #
#---------------------------------#

after_build:
  7z a ServiceBusExplorer.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*.*

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: ServiceBusExplorer.zip  # bin\$(configuration)\*.*
    name: ServiceBusExplorer

#---------------------------------#
#     GitHub PR notifications     #
#---------------------------------#

notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: SDw1gs4noXA0eUpBoBcbT2XNYwf0Bg7gHR/TpP2Y/gQS/QYST7toE0oRzoKV/2U6 # encrypted token from GitHub
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: GitHub
    auth_token:
      secure: SDw1gs4noXA0eUpBoBcbT2XNYwf0Bg7gHR/TpP2Y/gQS/QYST7toE0oRzoKV/2U6 # encrypted token from GitHub
    artifact: /.*\.*/           # upload all NuGet packages to release assets
    description: ServiceBus Explorer build %APPVEYOR_BUILD_VERSION%.
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only