// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.EventGrid
{
    using Microsoft.Rest;
    using Microsoft.Rest.Azure;

    /// <summary>
    /// Azure EventGrid Management Client
    /// </summary>
    public partial class EventGridManagementClient : ServiceClient<EventGridManagementClient>, IEventGridManagementClient, IAzureClient
    {
        public void SetApiVersion(string apiVersion = null)
        {
            if (!string.IsNullOrEmpty(apiVersion))
            {
                this.ApiVersion = apiVersion;
            }
        }
   }
}
