// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.EventGrid.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Properties of the delivery configuration information of the event
    /// subscription.
    /// </summary>
    public partial class DeliveryConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the DeliveryConfiguration class.
        /// </summary>
        public DeliveryConfiguration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeliveryConfiguration class.
        /// </summary>
        /// <param name="deliveryMode">Delivery mode of the event subscription.
        /// Possible values include: 'Queue'</param>
        /// <param name="queue">This property should be populated when
        /// deliveryMode is queue and represents information about the queue
        /// subscription.</param>
        public DeliveryConfiguration(string deliveryMode = default(string))
        {
            DeliveryMode = deliveryMode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets delivery mode of the event subscription. Possible
        /// values include: 'Queue'
        /// </summary>
        [JsonProperty(PropertyName = "deliveryMode")]
        public string DeliveryMode { get; set; }

    }
}
