// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.EventGrid.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents available Sku pricing tiers.
    /// </summary>
    public partial class NamespaceSku
    {
        /// <summary>
        /// Initializes a new instance of the NamespaceSku class.
        /// </summary>
        public NamespaceSku()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NamespaceSku class.
        /// </summary>
        /// <param name="name">The name of the SKU. Possible values include:
        /// 'Standard'</param>
        /// <param name="capacity">Specifies the number of Throughput Units
        /// that defines the capacity for the namespace. The property default
        /// value is
        /// 1 which signifies 1 Throughput Unit = 1MB/s ingress and 2MB/s
        /// egress per namespace. Min capacity is 1 and
        /// max allowed capacity is 20.</param>
        public NamespaceSku(string name = default(string), int? capacity = default(int?))
        {
            Name = name;
            Capacity = capacity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name of the SKU. Possible values include:
        /// 'Standard'
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets specifies the number of Throughput Units that defines
        /// the capacity for the namespace. The property default value is
        /// 1 which signifies 1 Throughput Unit = 1MB/s ingress and 2MB/s
        /// egress per namespace. Min capacity is 1 and
        /// max allowed capacity is 20.
        /// </summary>
        [JsonProperty(PropertyName = "capacity")]
        public int? Capacity { get; set; }

    }
}
