// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.EventGrid.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Properties of the namespace topic update.
    /// </summary>
    [Rest.Serialization.JsonTransformation]
    public partial class NamespaceTopicUpdateParameters
    {
        /// <summary>
        /// Initializes a new instance of the NamespaceTopicUpdateParameters
        /// class.
        /// </summary>
        public NamespaceTopicUpdateParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NamespaceTopicUpdateParameters
        /// class.
        /// </summary>
        /// <param name="eventRetentionInDays">Event retention for the
        /// namespace topic expressed in days. The property default value is 1
        /// day.
        /// Min event retention duration value is 1 day and max event retention
        /// duration value is 1 day.</param>
        public NamespaceTopicUpdateParameters(int? eventRetentionInDays = default(int?))
        {
            EventRetentionInDays = eventRetentionInDays;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets event retention for the namespace topic expressed in
        /// days. The property default value is 1 day.
        /// Min event retention duration value is 1 day and max event retention
        /// duration value is 1 day.
        /// </summary>
        [JsonProperty(PropertyName = "properties.eventRetentionInDays")]
        public int? EventRetentionInDays { get; set; }

    }
}
