// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.EventGrid.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Event Subscription.
    /// </summary>
    [Rest.Serialization.JsonTransformation]
    public partial class Subscription : Resource
    {
        /// <summary>
        /// Initializes a new instance of the Subscription class.
        /// </summary>
        public Subscription()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Subscription class.
        /// </summary>
        /// <param name="id">Fully qualified identifier of the
        /// resource.</param>
        /// <param name="name">Name of the resource.</param>
        /// <param name="type">Type of the resource.</param>
        /// <param name="provisioningState">Provisioning state of the event
        /// subscription. Possible values include: 'Creating', 'Updating',
        /// 'Deleting', 'Succeeded', 'Canceled', 'Failed',
        /// 'AwaitingManualAction', 'Deleted', 'DeleteFailed', 'CreateFailed',
        /// 'UpdatedFailed'</param>
        /// <param name="deliveryConfiguration">Information about the delivery
        /// configuration of the event subscription.</param>
        /// <param name="eventDeliverySchema">The event delivery schema for the
        /// event subscription. Possible values include:
        /// 'CloudEventSchemaV1_0'</param>
        /// <param name="filtersConfiguration">Information about the filter for
        /// the event subscription.</param>
        /// <param name="systemData">The system metadata relating to Event
        /// Subscription resource.</param>
        public Subscription(string id = default(string), string name = default(string), string type = default(string), string provisioningState = default(string), DeliveryConfiguration deliveryConfiguration = default(DeliveryConfiguration), string eventDeliverySchema = default(string), FiltersConfiguration filtersConfiguration = default(FiltersConfiguration), SystemData systemData = default(SystemData))
            : base(id, name, type)
        {
            ProvisioningState = provisioningState;
            DeliveryConfiguration = deliveryConfiguration;
            EventDeliverySchema = eventDeliverySchema;
            FiltersConfiguration = filtersConfiguration;
            SystemData = systemData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets provisioning state of the event subscription. Possible values
        /// include: 'Creating', 'Updating', 'Deleting', 'Succeeded',
        /// 'Canceled', 'Failed', 'AwaitingManualAction', 'Deleted',
        /// 'DeleteFailed', 'CreateFailed', 'UpdatedFailed'
        /// </summary>
        [JsonProperty(PropertyName = "properties.provisioningState")]
        public string ProvisioningState { get; private set; }

        /// <summary>
        /// Gets or sets information about the delivery configuration of the
        /// event subscription.
        /// </summary>
        [JsonProperty(PropertyName = "properties.deliveryConfiguration")]
        public DeliveryConfiguration DeliveryConfiguration { get; set; }

        /// <summary>
        /// Gets or sets the event delivery schema for the event subscription.
        /// Possible values include: 'CloudEventSchemaV1_0'
        /// </summary>
        [JsonProperty(PropertyName = "properties.eventDeliverySchema")]
        public string EventDeliverySchema { get; set; }

        /// <summary>
        /// Gets or sets information about the filter for the event
        /// subscription.
        /// </summary>
        [JsonProperty(PropertyName = "properties.filtersConfiguration")]
        public FiltersConfiguration FiltersConfiguration { get; set; }

        /// <summary>
        /// Gets or sets the system metadata relating to Event Subscription
        /// resource.
        /// </summary>
        [JsonProperty(PropertyName = "systemData")]
        public SystemData SystemData { get; set; }
    }
}
