// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Management.EventGrid.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Properties of the Topics Configuration.
    /// </summary>
    public partial class TopicsConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the TopicsConfiguration class.
        /// </summary>
        public TopicsConfiguration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TopicsConfiguration class.
        /// </summary>
        /// <param name="hostname">The hostname for the topics configuration.
        /// This is a read-only property.</param>
        public TopicsConfiguration(string hostname = default(string))
        {
            Hostname = hostname;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the hostname for the topics configuration. This is a read-only
        /// property.
        /// </summary>
        [JsonProperty(PropertyName = "hostname")]
        public string Hostname { get; private set; }

    }
}
