<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyVersion>1.0.0.1</AssemblyVersion>
		<RootNamespace>EventGridExplorerLibrary</RootNamespace>
		<AssemblyName>ServiceBusExplorer.EventGridExplorerLibrary</AssemblyName>
    <NoWarn>7035</NoWarn>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Messaging.EventGrid" />
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Azure.ResourceManager.EventGrid" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Microsoft.Rest.ClientRuntime" />
		<PackageReference Include="Microsoft.Rest.ClientRuntime.Azure" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Utilities\Utilities.csproj" />
	</ItemGroup>

</Project>
