// // Auto-added comment

// // <auto-generated>
// // Copyright (c) Microsoft Corporation. All rights reserved.
// // Licensed under the MIT License. See License.txt in the project root for
// // license information.
// //
// // Code generated by Microsoft (R) AutoRest Code Generator.
// // Changes may cause incorrect behavior and will be lost if the code is
// // regenerated.
// // </auto-generated>

// namespace EventGridExplorerLibrary
// {
//     using global::Azure.ResourceManager.Models;

//     /// <summary>
//     /// Namespace topic details.
//     /// </summary>
//     public partial class NamespaceTopic
//     {
//         /// <summary>
//         /// Initializes a new instance of the NamespaceTopic class.
//         /// </summary>
//         public NamespaceTopic()
//         {
//             CustomInit();
//         }

//         /// <summary>
//         /// Initializes a new instance of the NamespaceTopic class.
//         /// </summary>
//         /// <param name="id">Fully qualified identifier of the
//         /// resource.</param>
//         /// <param name="name">Name of the resource.</param>
//         /// <param name="type">Type of the resource.</param>
//         /// <param name="provisioningState">Provisioning state of the namespace
//         /// topic. Possible values include: 'Creating', 'Updating', 'Deleting',
//         /// 'Succeeded', 'Canceled', 'Failed', 'Deleted', 'DeleteFailed',
//         /// 'CreateFailed', 'UpdatedFailed'</param>
//         /// <param name="publisherType">Publisher type of the namespace topic.
//         /// Possible values include: 'Custom'</param>
//         /// <param name="inputSchema">This determines the format that is
//         /// expected for incoming events published to the topic. Possible
//         /// values include: 'CloudEventSchemaV1_0'</param>
//         /// <param name="eventRetentionInDays">Event retention for the
//         /// namespace topic expressed in days. The property default value is 1
//         /// day.
//         /// Min event retention duration value is 1 day and max event retention
//         /// duration value is 1 day.</param>
//         /// <param name="systemData">The system metadata relating to namespace
//         /// topic resource.</param>
//         public NamespaceTopic(string id = default(string), string name = default(string), string type = default(string), string provisioningState = default(string), string publisherType = default(string), string inputSchema = default(string), int? eventRetentionInDays = default(int?), SystemData systemData = default(SystemData))
//         {
//             CustomInit();
//         }

//         /// <summary>
//         /// An initialization method that performs custom operations like setting defaults
//         /// </summary>
//         partial void CustomInit();
//     }

       
// }
