name: Handle pull request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yml
    with: 
      release-version: '0.0.0'
      cache-build: false
